05/05/2016 05:00:52 PM - INFO - GUI display widget values successfully restored.
05/05/2016 05:00:52 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:00:52 PM - INFO - Controller turned off successfully.
05/05/2016 05:00:52 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/05/2016 05:00:52 PM - INFO - Controller turned on successfully.
05/05/2016 05:00:58 PM - INFO - Starting Exposure Stack with imcount 10, exptime 3.0, and filebase /home/lsst/Data/20160426.exp.3.0s.
05/05/2016 05:00:58 PM - ERROR - Executable exp_acq not found. Image not taken.
Traceback (most recent call last):
  File "./ccdctrl-dev-1.py", line 251, in expose
    filename = exposure.stack(mode, filebase, imcount, exptime, start)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 126, in stack
    im_acq(mode, filename, time)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 110, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
05/05/2016 05:01:03 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:01:03 PM - INFO - Controller turned off successfully.
05/05/2016 05:04:08 PM - INFO - GUI display widget values successfully restored.
05/05/2016 05:04:08 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:04:08 PM - INFO - Controller turned off successfully.
05/05/2016 05:04:08 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/05/2016 05:04:08 PM - INFO - Controller turned on successfully.
05/05/2016 05:04:14 PM - INFO - Starting 3.0s Exposure image with filebase /home/lsst/Data/20160426.exp.3.0s.
05/05/2016 05:04:14 PM - ERROR - Executable exp_acq not found. Image not taken
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 222, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 110, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
05/05/2016 05:04:50 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:04:50 PM - INFO - Controller turned off successfully.
05/05/2016 05:06:41 PM - INFO - GUI display widget values successfully restored.
05/05/2016 05:06:41 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:06:41 PM - INFO - Controller turned off successfully.
05/05/2016 05:06:41 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/05/2016 05:06:41 PM - INFO - Controller turned on successfully.
05/05/2016 05:07:11 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:07:11 PM - INFO - Controller turned off successfully.
05/05/2016 05:09:36 PM - INFO - GUI display widget values successfully restored.
05/05/2016 05:09:36 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:09:36 PM - INFO - Controller turned off successfully.
05/05/2016 05:09:36 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/05/2016 05:09:36 PM - INFO - Controller turned on successfully.
05/05/2016 05:09:54 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:09:54 PM - INFO - Controller turned off successfully.
05/05/2016 05:13:15 PM - INFO - GUI display widget values successfully restored.
05/05/2016 05:13:15 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:13:15 PM - INFO - Controller turned off successfully.
05/05/2016 05:13:15 PM - INFO - Turning on sta3800 controller (sta3800_setup).
05/05/2016 05:13:15 PM - INFO - Controller turned on successfully.
05/05/2016 05:13:18 PM - INFO - Starting 3.0s Exposure image with filebase /home/lsst/Data/20160426/preamp.in.exp.3.0s.
05/05/2016 05:13:18 PM - ERROR - Executable exp_acq not found. Image not taken
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 223, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 110, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
05/05/2016 05:13:56 PM - INFO - Starting 3.0s Dark image with filebase /home/lsst/Data/20160426/preamp.in.dark.3.0s.
05/05/2016 05:13:56 PM - ERROR - Executable dark_acq not found. Image not taken
Traceback (most recent call last):
  File "./ccdctrl-dev.py", line 223, in expose
    filename = exposure.im_acq(mode, filebase, exptime)
  File "/Users/adamsnyder/ccdcontroller/exposure.py", line 107, in im_acq
    "{0}".format(filename)])
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adamsnyder/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
05/05/2016 05:14:00 PM - INFO - Turning off sta3800 controller (sta3800_off).
05/05/2016 05:14:00 PM - INFO - Controller turned off successfully.
